# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

likeLtsg <- function(orthoM, envM, DL, DRL, mu, q, r) {
    .Call(`_xsdmMle_likeLtsg`, orthoM, envM, DL, DRL, mu, q, r)
}

parallelVectorSum <- function(x) {
    .Call(`_xsdmMle_parallelVectorSum`, x)
}

