// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// likeLtsg
NumericVector likeLtsg(NumericMatrix orthoM, NumericMatrix envM, NumericMatrix DL, NumericMatrix DRL, NumericVector mu, int q, int r);
RcppExport SEXP _xsdmMle_likeLtsg(SEXP orthoMSEXP, SEXP envMSEXP, SEXP DLSEXP, SEXP DRLSEXP, SEXP muSEXP, SEXP qSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type orthoM(orthoMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type envM(envMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DL(DLSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DRL(DRLSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(likeLtsg(orthoM, envM, DL, DRL, mu, q, r));
    return rcpp_result_gen;
END_RCPP
}
// parallelVectorSum
double parallelVectorSum(NumericVector x);
RcppExport SEXP _xsdmMle_parallelVectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelVectorSum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xsdmMle_likeLtsg", (DL_FUNC) &_xsdmMle_likeLtsg, 7},
    {"_xsdmMle_parallelVectorSum", (DL_FUNC) &_xsdmMle_parallelVectorSum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_xsdmMle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
