# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

like_ltsg <- function(mu, env_m, dl_mat, drl_mat, ortho_m, q, r) {
    .Call(`_xsdmMle_like_ltsg`, mu, env_m, dl_mat, drl_mat, ortho_m, q, r)
}

